apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ip-change-alert-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: ip-change-alert-pv
